spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "hello-world"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "../../target/wasm32-wasi/release/hello_world.wasm"
description = "A simple component that returns hello."
allowed_outbound_hosts = ["https://*:*"]
key_value_stores = ["default"]
[component.hello.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
