CREATE TABLE articletest (
   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   title varchar(40) NOT NULL,
   content text NOT NULL,
   authorname varchar(40) NOT NULL ,
   publisheddate date NOT NULL,
   publishedtime time,
   publisheddatetime timestamp,
   readtime bigint,
   coauthor text
);

INSERT INTO articletest (title, content, authorname, publisheddate) VALUES
(
   'My Life as a Goat',
   'I went to Nepal to live as a goat, and it was much better than being a butler.',
   'E. Blackadder',
   '2024-11-05'
),
(
   'Magnificent Octopus',
   'Once upon a time there was a lovely little sausage.',
   'S. Baldrick',
   '2024-11-06'
);
